[core]

name: Incisor
displayDescription:The Incisor is a light, fast moving tank armed with a weak, but very precise laser weapon, accurate even when fired on the move. 
maxHp: 820
price: 300
displayRadius: 27
radius: 27
mass: 20
fogOfWarSightRange: 5

[graphics]

# this is the body of the unit
    # the image that we will animate, make sure the image consists more than 2 frames and is aligned
    image: incisor_body.png
    image_shadow: AUTO
    shadowOffsetX: 1
    shadowOffsetY: 1
    dustEffect: true
    teamColorsOnTurret: true
    imageScale: 1

# the turret of the unit

[movement]
movementType: LAND
moveSpeed: 1.1
maxTurnSpeed: 1.2
turnAcceleration: 0.5
moveAccelerationSpeed: 0.0080
moveDecelerationSpeed: 0.06


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
maxAttackRange: 230
shootDelay: 0.56s
# this prevents the turret to have a slight turn when shooting
aimOffsetSpread: 0


[turret_1]
image: incisor_turret.png
x: 0
y: -4
turnSpeed: 4
projectile: laser
#where the projectile will spawn from, this is relative to the turret
barrelX: 0
barrelY: 26
recoilOffset: -0.7
recoilReturnTime: 0.5s
shoot_sound: ROOT:assets\audio\beams\lasrfir1.wav
shoot_sound_vol: 0.3
warmup: 20
chargeEffectImage: ROOT:assets\projectiles\beams\red_charge_small.png

[projectile_laser]
directDamage: 35
life:20
speed:26
targetSpeed:26
trailEffect:CUSTOM:wingTrail
trailEffectRate:0.2
explodeEffect:CUSTOM:hit

[effect_wingTrail]

image:  ROOT:assets\projectiles\beams\red_beam.png
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 0.1
yOffsetRelative: -7
life: 30
alpha: 1

[effect_hit]
image: ROOT:assets\projectiles\beams\red_hit.png
scaleFrom: 0.3
scaleTo: 0.3
total_frames: 3
animateFrameStart: 0
animateFrameEnd: 3
animateFrameSpeed: .4



[decal_shadow]
image: SHADOW:incisor_turret.png
xOffsetRelative: 2
yOffsetRelative: 7
layer: afterBody
alpha: 0.5
basePositionFromTurret: 1

