[core]
name: extractor
displayLocaleKey: extractor
mass: 9000
#footprint used for collisions with units (left, up, right, down)
footprint: -1,-1,1,1
#used for placement, and placement of other buildings
constructionFootprint: -2,-2,2,2
buildingSelectionOffset:4
radius: 40
displayRadius:40
isBuilding: true
placeOnlyOnResPool: true
numBitsOnDeath: 16
hideScorchMark: true
effectOnDeath: resourcePoolSmoke
explodeTypeOnDeath: buildingNoShockwaveOrSmoke
price: 700
maxHp:660
techLevel: 1
buildSpeed: 0.0010
#unfinished will add metal resource
generation_resources: metal=0.05
generation_delay: 0

[graphics]
image: cortex_extractor.png

[movement]
movementType: BUILDING

[attack]
canAttack:false

[decal_spin]
image: 