[core]
name: extractor
displayLocaleKey: extractor
mass: 9000
#footprint used for collisions with units (left, up, right, down)
footprint: -1,-1,1,1
#used for placement, and placement of other buildings
constructionFootprint: -2,-2,2,2
buildingSelectionOffset:4
radius: 40
displayRadius:40
isBuilding: true
placeOnlyOnResPool: true
numBitsOnDeath: 16
hideScorchMark: true
effectOnDeath: resourcePoolSmoke
explodeTypeOnDeath: buildingNoShockwaveOrSmoke
price: metal=50
maxHp:660
techLevel: 1
buildSpeed: 0.0010
#unfinished will add metal resource
generation_resources: metal=0.05
generation_delay: 0

[graphics]
image: cortex_extractor.png
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1

[movement]
movementType: BUILDING

[attack]
canAttack:false

[turret_1]
x: 0
y: 0
image: cortex_extractor_spin.png
idleSpin: 1.5

[decal_shadow]
image: SHADOW:cortex_extractor_spin.png
xOffsetRelative: -1
yOffsetRelative: 2
basePositionFromTurret: 1
alpha: 0.5
layer: afterBody



