[core]

name: rascal
displayDescription: Rascals are cheap and quick vehicles used for scouting, and raiding your enemies economy.
maxHp: 90
price: 0
streamingCost: metalresource=26, energyresource=270
displayRadius: 15
radius: 15
mass: 20
fogOfWarSightRange: 25
[graphics]
image: rascal.png
total_frames: 2
animation_moving_speed: 2
animation_moving_start: 0
animation_moving_end: 1
image_shadow: AUTO
shadowOffsetX: 1
shadowOffsetY: 1
dustEffect: true
teamColorsOnTurret: true
imageScale: 1

[movement]
movementType: LAND
moveSpeed: 2.5
maxTurnSpeed: 2.5
turnAcceleration: 0.5
moveAccelerationSpeed: 0.090
moveDecelerationSpeed: 0.1


[attack]
canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits: true
canAttackUnderwaterUnits: false
maxAttackRange: 180
shootDelay: 0.76s
# this prevents the turret to have a slight turn when shooting
aimOffsetSpread: 0


[turret_1]
image: rascal_top.png
x: 0
y: 1
turnSpeed: 4
projectile: laser
#where the projectile will spawn from, this is relative to the turret
barrelX: 7.5
barrelY: 13
recoilOffset: -0.7
recoilReturnTime: 0.5s
shoot_sound: ROOT:assets\audio\beams\lasrfir1.wav
shoot_sound_vol: 0.3
warmup: 20
chargeEffectImage: ROOT:assets\projectiles\beams\yellow_charge_small.png

[projectile_laser]
directDamage: 35
life:20
speed:26
targetSpeed:26
trailEffect:CUSTOM:wingTrail
trailEffectRate:0.2
explodeEffect:CUSTOM:hit

[effect_wingTrail]

image:  ROOT:assets\projectiles\beams\yellow_beam.png
attachedToUnit: false
scaleFrom: 0.5
scaleTo: 0.1
yOffsetRelative: -7
life: 30
alpha: 1

[effect_hit]
image: ROOT:assets\projectiles\beams\yellow_hit.png
scaleFrom: 0.3
scaleTo: 0.3
total_frames: 3
animateFrameStart: 0
animateFrameEnd: 3
animateFrameSpeed: .4


[turret_radar]


image: rascal_radar.png
x: -3
y: -11
attachedTo: 1
canShoot: false
idleSpin:2
canAttackFlyingUnits: false
canAttackLandUnits: false
canAttackUnderwaterUnits: false

[decal_shadow]
image: SHADOW:rascal_top.png
xOffsetRelative: -1
yOffsetRelative: -1
layer: beforeBody
alpha: 0.5
basePositionFromTurret: 1

